name: Sync to Hugging Face hub

on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Set up DVC
      - name: Set up DVC
        run: |
          pip install dvc  # Install DVC
          dvc pull  # Pull data and model from DVC remote

      # Push to Hugging Face Hub
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git add .  # Add any changes to git
          git commit -m "Sync model and data"
          git push --force https://ved-1123:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/ved-1123/pumpkin-app main
          
      # Push any DVC-tracked files back to DVC remote
      - name: Push DVC files
        run: |
          dvc push  # Push changes (model, data) to DVC remote
